"""Every knob the app has, and — for each one — why it is allowed to exist in the environment.

THE RULE THIS FILE ENFORCES: a teammate with this repository must be able to rebuild the whole
deployment knowing exactly two values, the OpenAI key and the domain. Everything else is either
generated by the provisioning script, derived from the deployment's own topology, or simply the
default written here. Production ran for a while with a dozen variables set by hand that only
restated a default below; the cost is not the typing, it is that reading this file stopped
telling you what production does.

So every field is declared through one of four helpers, and the helper IS the classification:

  env_specific()  A human must supply it, and no script can invent it. ONLY the OpenAI key and
                  the public URL are allowed to be this — `ENV_SPECIFIC_FIELDS` is the whole
                  list, and `tests/test_config_surface.py` fails if it grows.
  secret()        Per-deployment, but MINTED rather than carried: the provisioning script
                  generates it (`python -c "import secrets; print(secrets.token_hex(32))"`) and
                  never has to know a previous value. Replicating the deploy does not require
                  learning these. `startup_checks.py` refuses to boot on a published placeholder.
  infra()         Derived from the deployment's shape, not from taste: the database URL, the
                  sidecar's internal DNS name, which environment this is. The checked-in
                  provisioning script sets these verbatim; they are not choices a human makes.
  code_default()  The value production runs on, and it lives HERE. Setting one of these in
                  Railway is the mistake described above: it forks the running config away from
                  the repo. If you want to change it, change it here and deploy.

Adding a setting means picking one of the four — there is no plain-default form, and the surface
test fails on a field that skipped the decision.
"""

from decimal import Decimal
from enum import StrEnum
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from pydantic import AliasChoices, Field, field_validator
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, SettingsConfigDict

# Repo root, so the backend picks up the shared .env whether it is started from
# the repo root or from backend/.
REPO_ROOT = Path(__file__).resolve().parents[2]


class SettingClass(StrEnum):
    """Why a setting is allowed to be set in the environment — or why it must not be."""

    ENV_SPECIFIC = "env-specific"
    SECRET = "secret"
    INFRA = "infra"
    CODE_DEFAULT = "code-default"


# Where each field stashes its class. `json_schema_extra` is inert at runtime; it is just the
# only per-field slot pydantic gives us that survives on `Settings.model_fields`.
_CLASS_KEY = "penny_setting_class"


def _classified(setting_class: SettingClass, default: Any, **kwargs: Any) -> Any:
    return Field(default, json_schema_extra={_CLASS_KEY: setting_class.value}, **kwargs)


def env_specific(default: Any, **kwargs: Any) -> Any:
    """A human must supply this per deployment. Only two fields may use it."""
    return _classified(SettingClass.ENV_SPECIFIC, default, **kwargs)


def secret(default: Any = None, **kwargs: Any) -> Any:
    """Generated at provisioning time, never copied between deployments."""
    return _classified(SettingClass.SECRET, default, **kwargs)


def infra(default: Any = None, **kwargs: Any) -> Any:
    """Follows from the deployment's topology; the provisioning script sets it verbatim."""
    return _classified(SettingClass.INFRA, default, **kwargs)


def code_default(default: Any, **kwargs: Any) -> Any:
    """The value production runs on. Do NOT set this in Railway — change it here."""
    return _classified(SettingClass.CODE_DEFAULT, default, **kwargs)


# The user's contract, in one line: "the only environment-specific behaviour is the OpenAI api
# key (and the domain name)". Anything else that wants to be env-specific is really a secret, a
# piece of infra, or a default someone did not want to commit to.
ENV_SPECIFIC_FIELDS: frozenset[str] = frozenset({"openai_api_key", "app_public_url"})


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=(REPO_ROOT / ".env", REPO_ROOT / "backend" / ".env"),
        env_file_encoding="utf-8",
        extra="ignore",
        # Aliased fields still have to be constructible by field name in tests.
        populate_by_name=True,
    )

    # INFRA — which deployment this is. Production sets it so `startup_checks` becomes fatal and
    # CORS for the Vite dev server on :5173 goes away; docker-compose and .env.example set "dev".
    # Not a taste knob, and not something a teammate has to be told.
    env: Literal["dev", "test", "production"] = infra("dev")

    # --- OpenAI -----------------------------------------------------------------------------
    # ENV-SPECIFIC (and secret) — one of the two values a teammate genuinely has to bring. Unset
    # is legal: the app boots and serves the feed with extraction disabled.
    openai_api_key: str | None = env_specific(None)
    # INFRA — only set when pointing at a proxy or an Azure-compatible gateway, which is a
    # property of where you are deployed, not a preference. Unset means api.openai.com.
    openai_base_url: str | None = infra(None)
    # CODE-DEFAULT — dated snapshots, never the floating alias: a silent model swap changes
    # extraction quality with no diff to point at. Which is exactly why the pin belongs in the
    # repo and not in a dashboard field nobody reviews.
    llm_model_extract: str = code_default("gpt-5.5-2026-04-23")
    llm_model_report: str = code_default("gpt-5.5-2026-04-23")

    # --- Database ---------------------------------------------------------------------------
    # INFRA — on Railway this is a reference to the Postgres addon (${{Postgres.DATABASE_URL}}),
    # so its value is a fact about the project, not a decision. Required in production.
    database_url: str | None = infra(None)
    # INFRA — the local test database. Read only by the test suite; DB tests skip without it, and
    # a production process never looks at it.
    test_database_url: str | None = infra(
        None,
        validation_alias=AliasChoices("PENNY_TEST_DATABASE_URL", "TEST_DATABASE_URL"),
    )

    # --- Auth — session cookie carrying household_id ------------------------------------------
    # SECRET — signs the HttpOnly session cookie. Minted at provisioning; rotating it logs every
    # household out.
    session_secret: str | None = secret()
    # CODE-DEFAULT — how long a login lasts. A product decision, so it belongs in the repo.
    session_max_age_days: int = code_default(30)

    # --- GOWA WhatsApp sidecar ----------------------------------------------------------------
    # INFRA — the sidecar's internal Railway DNS name and port. Unset disables outbound WhatsApp,
    # which is the supported "API only" mode.
    gowa_url: str | None = infra(None)
    # SECRET — "user:pass", and the same pair as APP_BASIC_AUTH on the GOWA service. GOWA splits
    # it on ":" and exits unless it gets exactly two parts, so the password may contain no colon.
    gowa_basic_auth: str | None = secret()
    # SECRET — HMAC-SHA256 key for X-Hub-Signature-256 on inbound webhooks. Must match GOWA's
    # WHATSAPP_WEBHOOK_SECRET or the webhook is unauthenticated.
    whatsapp_webhook_secret: str | None = secret()

    # SECRET — shared secret for the Railway cron service calling /api/internal/tick.
    internal_tick_secret: str | None = secret()

    # --- Spend guards -------------------------------------------------------------------------
    # CODE-DEFAULT both. These are the numbers the product is willing to spend, which is a
    # reviewable decision and not an environment fact.
    import_max_spend_usd: Decimal = code_default(Decimal("25"))
    llm_monthly_budget_usd_per_household: Decimal = code_default(Decimal("15"))

    # --- Voice note transcription ---------------------------------------------------------
    # All CODE-DEFAULT: behaviour, not environment. In a family care chat "Mum had a fall this
    # morning" is often SPOKEN. Without this the message reaches the timeline as "[voice note]"
    # and extraction sees nothing at all.
    #
    # The kill switch. False leaves every voice note as the placeholder — the pre-transcription
    # behaviour, and the thing to reach for if the audio bill or the sidecar misbehaves. Flipping
    # it is a commit, so the incident leaves a trace.
    transcribe_voice_notes: bool = code_default(True)
    # The cheap model, deliberately: a 20-second voice note is a small job. Raise it to
    # "gpt-4o-transcribe" if accuracy on names and doses is not good enough. Every value here
    # must have a per-minute price in `app.llm.pricing.AUDIO_PRICES_PER_MINUTE`, or
    # transcription refuses to run rather than spending money it cannot account for.
    transcription_model: str = code_default("gpt-4o-mini-transcribe")
    # A 40-minute audio file in a family chat is somebody forwarding a podcast, not care
    # signal — and it is the shape that quietly costs real money (300s at the mini rate is
    # $0.015; 40 minutes is $0.12, every time it is replayed). Duration is read from the GOWA
    # payload, so a note whose duration is not declared is not refused by this gate; the byte
    # cap below is the backstop for that case.
    transcription_max_seconds: int = code_default(300)
    # Hard cap on what we will pull from the sidecar into memory. A one-minute WhatsApp voice
    # note is well under 200 KB, so 20 MB is far past any real one and exists only so a
    # misbehaving (or hostile) media response cannot be unbounded.
    transcription_max_bytes: int = code_default(20 * 1024 * 1024)

    # CODE-DEFAULT — the timezone every household's day boundaries are computed in until
    # households carry their own. A UK product; when that stops being true it becomes a column,
    # not an environment variable.
    default_timezone: str = code_default("Europe/London")
    # CODE-DEFAULT — the single service serves the built SPA same-origin, in every environment
    # including local. Set it false only when running Vite on :5173 and wanting the API to stop
    # answering for the frontend routes.
    serve_frontend: bool = code_default(True)

    # --- Extraction cadence ---------------------------------------------------------------
    # Both CODE-DEFAULT. Extraction is charged per CALL, not per message: ~1,400 tokens of system
    # prompt, care brief and open-events block ride along with every request regardless of how
    # much conversation is in it. Extracting on every inbound message measured at $0.00763/message
    # against a planned $0.00042 — 18x — because a five-message run pays that fixed tax
    # thirteen times over. Batching also extracts BETTER: a thread about one appointment
    # arrives finished and becomes one event instead of three partials that then need paid
    # merge calls to reconcile.
    #
    # These two are OR-ed, and the gate lives in `extraction.service` so that every caller
    # inherits it. Raising the count saves money and adds latency to the feed; the age is what
    # bounds that latency, so lowering the count without also lowering the age is the safe
    # direction to experiment in.
    extract_min_unextracted: int = code_default(40)
    # NOT an int: tests and a "flush fast" incident setting both want fractions of an hour.
    # The age is measured from the oldest waiting message's `sent_at`.
    extract_max_age_hours: float = code_default(6.0)

    # --- Group onboarding -----------------------------------------------------------------
    # ENV-SPECIFIC — the other of the two. Where a family is sent after Penny is added to their
    # group; it goes into the welcome message, so a wrong value here is a dead link in the first
    # thing the product ever says. The default is this deployment's domain, which is what makes a
    # fork or a staging copy the only place that has to override it.
    app_public_url: str = env_specific("https://pennyai.chat")
    # CODE-DEFAULT — the kill switch. False makes an unknown group a silent 200 again, which is
    # the pre-onboarding behaviour and the thing to reach for if the WhatsApp number gets out.
    # It is a commit rather than a dashboard toggle on purpose: a deploy is ~2 minutes and the
    # alternative is a production behaviour change with no diff anywhere.
    onboarding_enabled: bool = code_default(True)
    # CODE-DEFAULT — the blast radius of open onboarding is the OpenAI bill, not data: anyone who
    # learns the number can mint households, and every household runs extraction. This cap is
    # what stops that starving real families of their budget.
    onboarding_max_households: int = code_default(25)
    # CODE-DEFAULT — households.care_recipient_name is NOT NULL and at provision time nobody has
    # told us who is being cared for. "Still the placeholder" is the signal that first-run setup
    # is needed, so this string is compared against, not just displayed — change it and every
    # existing household looks configured. Which is also why it could never be an env var: two
    # deployments with different values would disagree about which households are set up.
    onboarding_placeholder_care_recipient: str = code_default("your family member")
    # CODE-DEFAULT — how long after process start a `group.joined` burst is treated as whatsmeow
    # app-state sync rather than a human adding Penny to a chat. whatsmeow re-emits JoinedGroup
    # for every group the account was ALREADY in while it replays app state after a connect, and
    # every deploy reconnects — which is how a login password reached group chats nobody had
    # invited Penny to. Nothing on the event distinguishes the two cases; the only signal is that
    # the burst arrives seconds after the socket came up.
    #
    # A join refused in this window is still RECORDED, so it can never provision later either
    # (see `app.groups`). The cost is that a family who add Penny in the first three minutes
    # after a deploy get no welcome and a human sends their credentials by hand — a support
    # message, against a password in a stranger's chat, which cannot be unsent.
    #
    # 0 disables the window, which is only safe on a number that belongs to no other groups.
    startup_quiet_period_seconds: float = code_default(180.0)
    # CODE-DEFAULT — the third gate, and the one that covers the day this ships. The other two
    # can both be open at once: on a brand-new ledger every pre-existing group is a "first
    # sighting", and a sync burst that lands a little more than `startup_quiet_period_seconds`
    # after boot clears the quiet window too. That combination was reproducible against the
    # shipped code — eight joins, eight households, eight passwords — and it is the exact state
    # of production on the first deploy, when `known_groups` is empty.
    #
    # The signal is cardinality: a human adds Penny to ONE group at a time, whereas whatsmeow
    # replays every group the account already belonged to at once. So a welcome is held for this
    # long and only sent if no other group appeared in the meantime. Every genuine welcome is
    # therefore ~45s late, which is the whole cost. 0 disables the guard.
    join_burst_window_seconds: float = code_default(45.0)

    @field_validator("database_url")
    @classmethod
    def _require_asyncpg_driver(cls, value: str | None) -> str | None:
        """Railway hands out postgresql://; asyncpg needs the driver in the scheme."""
        if value is None:
            return None
        for scheme in ("postgres://", "postgresql://"):
            if value.startswith(scheme):
                return "postgresql+asyncpg://" + value[len(scheme) :]
        return value

    @property
    def sync_database_url(self) -> str | None:
        """Same URL for tools that speak psycopg/DBAPI rather than asyncpg (e.g. Alembic)."""
        if self.database_url is None:
            return None
        return self.database_url.replace("+asyncpg", "", 1)


def _class_of(field: FieldInfo) -> SettingClass | None:
    extra = field.json_schema_extra
    if isinstance(extra, dict) and isinstance(value := extra.get(_CLASS_KEY), str):
        return SettingClass(value)
    return None


# The whole table, derived from the fields themselves so it cannot drift from them. `None` means
# a field skipped the decision, which is what the surface test exists to catch.
SETTING_CLASSES: dict[str, SettingClass | None] = {
    name: _class_of(field) for name, field in Settings.model_fields.items()
}


def settings_in_class(setting_class: SettingClass) -> frozenset[str]:
    """Field names in one class — used by the surface test and by deployment docs."""
    return frozenset(name for name, found in SETTING_CLASSES.items() if found is setting_class)


@lru_cache
def get_settings() -> Settings:
    return Settings()
