"""initial schema

All nine tables from the plan's Data model, plus five deliberate additions the plan's own
behaviours need and its column lists omit:

  * llm_runs.cost_usd numeric(10,6), reasoning_tokens, cached_input_tokens, attempts,
    latency_ms, response_id, request_fingerprint — IMPORT_MAX_SPEND_USD and the monthly
    per-household budget are both a SUM over cost_usd. Without the column, every spend guard
    in the plan is uncomputable and reasoning tokens (billed as output at $30/M) are invisible.
  * messages.source_ordinal — the .txt parser's line index; export timestamps carry no seconds,
    so this is the only stable tiebreak when a dozen messages share a minute.
  * events.occurrences jsonb, user_edited_fields text[], pinned boolean — required by the merge
    behaviour ("mentioned 3x"), by "a human edit is permanent", and by Split respectively.
  * imports.status / imports.error — GET /api/imports/{id} returns a status in
    pending|importing|extracting|complete|failed and a rendered error sentence; neither is
    derivable from the other columns.
  * reports.summary / urgent_flag / urgent_reason / questions_for_the_doctor / watch_items /
    data_gaps — top-level fields of the GET /api/reports/{id} body in docs/api-contract.md.

Revision ID: 11455b7b9afa
Revises:
Create Date: 2026-07-25 20:15:42.347048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11455b7b9afa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("care_recipient_name", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), server_default=sa.text("'Europe/London'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
        sa.UniqueConstraint("username", name=op.f("uq_households_username")),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("file_sha256", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inserted_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dayfirst", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'importing', 'extracting', 'complete', 'failed')",
            name=op.f("ck_imports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_imports_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
        sa.UniqueConstraint("household_id", "file_sha256", name="uq_imports_household_file_sha256"),
    )
    op.create_table(
        "llm_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("reasoning_effort", sa.Text(), nullable=True),
        sa.Column("request_fingerprint", sa.Text(), nullable=True),
        sa.Column("response_id", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_llm_runs_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_runs")),
    )
    op.create_index(
        "ix_llm_runs_household_created_at",
        "llm_runs",
        ["household_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("wa_jid", sa.Text(), nullable=True),
        sa.Column("wa_lid", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_members_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
    )
    op.create_index(
        "ix_members_household_lower_display_name",
        "members",
        ["household_id", sa.literal_column("lower(display_name)")],
        unique=False,
    )
    op.create_index(
        "uq_members_household_wa_jid",
        "members",
        ["household_id", "wa_jid"],
        unique=True,
        postgresql_where=sa.text("wa_jid IS NOT NULL"),
    )
    op.create_index(
        "uq_members_household_wa_lid",
        "members",
        ["household_id", "wa_lid"],
        unique=True,
        postgresql_where=sa.text("wa_lid IS NOT NULL"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("urgent_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("urgent_reason", sa.Text(), nullable=True),
        sa.Column(
            "sections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "questions_for_the_doctor",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "watch_items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "data_gaps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'complete', 'failed')", name=op.f("ck_reports_status")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_reports_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_table(
        "whatsapp_links",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("group_external_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'linked')", name=op.f("ck_whatsapp_links_status")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_whatsapp_links_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("household_id", name=op.f("pk_whatsapp_links")),
        sa.UniqueConstraint("group_external_id", name=op.f("uq_whatsapp_links_group_external_id")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "occurred_at_precision", sa.Text(), server_default=sa.text("'exact'"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("actor_member_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_message_ids",
            sa.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "source_excerpts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurrences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "user_edited_fields",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('symptom', 'appointment', 'medication', 'note')", name=op.f("ck_events_kind")
        ),
        sa.CheckConstraint(
            "occurred_at_precision IN ('exact', 'day', 'week', 'month', 'unknown')",
            name=op.f("ck_events_occurred_at_precision"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_member_id"],
            ["members.id"],
            name=op.f("fk_events_actor_member_id_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["llm_runs.id"],
            name=op.f("fk_events_extraction_run_id_llm_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_events_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_household_occurred_at_id",
        "events",
        ["household_id", sa.literal_column("occurred_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_events_household_dedup_key", "events", ["household_id", "dedup_key"], unique=True
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("sender_wa_jid", sa.Text(), nullable=True),
        sa.Column("sender_wa_lid", sa.Text(), nullable=True),
        sa.Column("sender_display_name", sa.Text(), nullable=True),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ordinal", sa.Integer(), nullable=True),
        sa.Column("message_type", sa.Text(), server_default=sa.text("'text'"), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('gowa', 'whatsapp_export', 'manual')", name=op.f("ck_messages_provider")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_messages_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_messages_member_id_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_household_sent_at_unextracted",
        "messages",
        ["household_id", "sent_at"],
        unique=False,
        postgresql_where=sa.text("extracted_at IS NULL"),
    )
    op.create_index(
        "uq_messages_household_content_hash",
        "messages",
        ["household_id", "content_hash"],
        unique=True,
    )
    op.create_index(
        "uq_messages_household_provider_message_id",
        "messages",
        ["household_id", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_messages_household_provider_message_id",
        table_name="messages",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_index("uq_messages_household_content_hash", table_name="messages")
    op.drop_index(
        "ix_messages_household_sent_at_unextracted",
        table_name="messages",
        postgresql_where=sa.text("extracted_at IS NULL"),
    )
    op.drop_table("messages")
    op.drop_index("uq_events_household_dedup_key", table_name="events")
    op.drop_index(
        "ix_events_household_occurred_at_id",
        table_name="events",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("events")
    op.drop_table("whatsapp_links")
    op.drop_table("reports")
    op.drop_index(
        "uq_members_household_wa_lid",
        table_name="members",
        postgresql_where=sa.text("wa_lid IS NOT NULL"),
    )
    op.drop_index(
        "uq_members_household_wa_jid",
        table_name="members",
        postgresql_where=sa.text("wa_jid IS NOT NULL"),
    )
    op.drop_index("ix_members_household_lower_display_name", table_name="members")
    op.drop_table("members")
    op.drop_index("ix_llm_runs_household_created_at", table_name="llm_runs")
    op.drop_table("llm_runs")
    op.drop_table("imports")
    op.drop_table("households")
    # ### end Alembic commands ###
