"""known_groups join-safety ledger

The table that makes join-only onboarding possible. Penny is paired to a real WhatsApp account
that already belonged to other people's group chats, and onboarding provisioned a household on
any message from any unknown group — so the welcome message, which contains a login and a
password, went into all of them. `whatsapp_links` cannot answer the question that would have
stopped it, because a row there IS a household: by the time a group is in that table it has
already been provisioned. This table answers "have we ever seen this group before?" for groups
that have no household and must never be given one.

Two columns, no `household_id`, and that is the point rather than an oversight — see the model
docstring and `app.groups`. A row's mere existence is the whole meaning.

The primary key is the arbiter for `INSERT ... ON CONFLICT DO NOTHING ... RETURNING`, which is
how `observe_group` decides "first time we have ever seen this" from whether a row was actually
inserted rather than from a SELECT that a concurrent delivery can race. Nothing else is needed:
no separate unique index, and no index on `first_seen_at`, which is only ever read by a human
asking when a particular group turned up.

Empty on deploy, by design. Every group Penny is already in is therefore "unseen" the first
time it speaks after this ships — which is exactly why `observe_group` returning True is not on
its own permission to send anything, and why the startup quiet period exists.

Revision ID: 12797385345a
Revises: 7729fdd8a397
Create Date: 2026-07-26 01:40:59.024934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12797385345a"
down_revision: str | Sequence[str] | None = "7729fdd8a397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "known_groups",
        sa.Column("group_external_id", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_external_id", name=op.f("pk_known_groups")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping the ledger makes every group unseen again, so the next event from a group Penny
    # has been sitting in for months reads as a first sighting. Harmless only because the code
    # that goes back with it is the code that stopped greeting on messages at all — rolling
    # back this migration WITHOUT rolling back the application is how the incident repeats.
    op.drop_table("known_groups")
    # ### end Alembic commands ###
