"""households.session_version for session revocation

The counter the signed session cookie is minted against. `require_household` compares the
version in the cookie to this column and 401s on a mismatch, so bumping it — on a password
change, or on POST /api/household/sign-out-everywhere — invalidates every cookie that household
has anywhere. Before this column the only way to revoke a stolen 30-day cookie was rotating
SESSION_SECRET, which signs every household out of every device.

NOT NULL DEFAULT 1 rather than DEFAULT 0, and that choice is the whole backfill story: cookies
minted before this migration carry no version at all and `read_session_cookie` reads them as 1,
so deploying this signs nobody out. Their first bump revokes them like any other cookie.

Cheap on any table Penny will ever have: Postgres 11+ stores a non-volatile column default in
the catalogue instead of rewriting every row, so the ADD COLUMN takes a brief ACCESS EXCLUSIVE
lock and returns.

Revision ID: 7729fdd8a397
Revises: 11455b7b9afa
Create Date: 2026-07-25 23:56:06.349810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7729fdd8a397"
down_revision: str | Sequence[str] | None = "11455b7b9afa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "households",
        sa.Column("session_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading throws away every household's revocation counter, so a cookie minted at
    # version 3 comes back as "no version" = version 1 and is honoured again. Re-upgrading
    # resets the column to 1, which matches — that is the cost of going backwards here, and it
    # is why a rollback after a compromise wants a SESSION_SECRET rotation as well.
    op.drop_column("households", "session_version")
    # ### end Alembic commands ###
